import { createHmac, createHash } from "node:crypto";
import type { CanonFactCandidateV2, ExperienceEvidenceV2, ObservableSignalV2 } from "../../src/types";
import { evidenceFromClaim, groundClaim, hashArtifact, sourceForArtifact, type EvidenceFinding, type GroundedClaim } from "./evidence";
import { assessmentContractIdentity, canonicalAuthorizationPayload, repairContext, sameMac, signExperiencePlan, verifyExperienceStageTicket, verifyRepairAuthorization } from "./scheduler";
import type { AssessExperienceRequest, AssessmentContractProjection, AssessmentState, AssessorDependencies, ExperienceAssessment, ExperienceLedgerPatch, ExperienceOperationResult, ExperiencePublicationPermit, ExperienceRepairToken, ExperienceStagePlan, PublicationPermitContext, RepairTokenContext, SemanticBlueprintVerdict, SemanticEvidenceClaim } from "./types";
import { adapterAppliesTo, isRuleAdapterId, runRuleAdapter, type RealizationBinding, type RealizationSlot } from "./ruleAdapters";
import type { GenericRuleAdapterId } from "./types";
import { canonFactCandidateId, cleanAuthorizationValue, evidenceRootHash, issuePublicationPermit, ledgerPatchHash, publicationPermitContext, publicationPermitDigest, sortedEvidenceBindings, verifyPublicationPermit as verifyPermit } from "./publication";
import { canonicalRoleKey, validTrustedRoleBindings } from "./roles";

export { verifyPublicationPermit } from "./publication";

const repairDomain = "reading-experience:repair:v1";
const invalidModel = (jobId: string): ExperienceOperationResult<never> => ({ ok: false, error: { code: "invalid_model_output", message: "Semantic judge returned an invalid verdict.", stage: "assessment", retryable: false, jobId } });
const unavailable = (jobId: string): ExperienceOperationResult<never> => ({ ok: false, error: { code: "model_unavailable", message: "Semantic judge is unavailable.", stage: "assessment", retryable: true, jobId } });
const freeze = <T>(value: T): T => { if (value && typeof value === "object" && !Object.isFrozen(value)) { for (const child of Object.values(value as object)) freeze(child); Object.freeze(value); } return value; };
const snapshot = <T>(value: T): T | undefined => { try { return freeze(structuredClone(value)); } catch { return undefined; } };
const sign = (domain: string, payload: unknown, secret: string): string => createHmac("sha256", secret).update(domain).update("\u001f").update(canonicalAuthorizationPayload(payload)).digest("base64url");
const artifactHashSafe = (request: AssessExperienceRequest): string => { try { return hashArtifact(request.artifact); } catch { return "invalid-artifact"; } };
const failure = (request: AssessExperienceRequest, id: string): ExperienceOperationResult<ExperienceAssessment> => ({ ok: true, value: { status: "rejected", artifactKind: request.artifact.kind, failedRuleIds: [id], message: "Assessment authorization is invalid." } });
const unique = (ids: string[]): string[] => [...new Set(ids)].sort();

function validArtifact(value: unknown): value is AssessExperienceRequest["artifact"] {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const item = value as Record<string, unknown>;
  if (item.kind === "blueprint") return Object.keys(item).every((key) => key === "kind" || key === "value") && item.value !== null && typeof item.value === "object" && !Array.isArray(item.value) && Object.keys(item.value as object).length > 0;
  if (item.kind !== "chapter" && item.kind !== "retcon_revision") return false;
  if (Object.keys(item).some((key) => !["kind", "chapterId", "revisionId", "title", "paragraphs"].includes(key))) return false;
  return typeof item.chapterId === "string" && !!item.chapterId.trim() && typeof item.revisionId === "string" && !!item.revisionId.trim() && typeof item.title === "string" && !!item.title.trim() && Array.isArray(item.paragraphs) && item.paragraphs.length > 0 && item.paragraphs.every((paragraph) => typeof paragraph === "string" && paragraph.length > 0);
}
function stageMatches(plan: ExperienceStagePlan, artifact: AssessExperienceRequest["artifact"]): boolean {
  if (artifact.kind === "blueprint") return plan.stage === "blueprint" || plan.stage === "rewrite";
  if (artifact.kind === "retcon_revision") return plan.stage === "retcon" || plan.stage === "rewrite";
  return plan.stage === "opening" || plan.stage === "continuation" || plan.stage === "rewrite";
}
function stateMatches(plan: ExperienceStagePlan, state: AssessmentState): boolean {
  return plan.ticket.activationId === state.activationId && plan.ticket.branchId === state.branchId && plan.ticket.expectedCanonVersion === state.canonVersion && plan.ticket.ledgerRevision === state.ledgerRevision && plan.ticket.attempt === state.attempt && plan.artifactBindingId === state.artifactBindingId && !state.consumedTicketIds.includes(plan.ticket.id);
}
function validAssessmentContract(plan: ExperienceStagePlan): plan is ExperienceStagePlan & { assessmentContract: AssessmentContractProjection } {
  const value = plan.assessmentContract as unknown;
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const projection = value as Record<string, unknown>;
  if (Object.keys(projection).sort().join("|") !== ["contractRevisionId", "dimensions", "identityHash", "prohibitions", "promises", "ruleGraphVersion", "schemaVersion", "synthesis", "version"].sort().join("|")) return false;
  if (projection.version !== 1 || projection.schemaVersion !== 2 || projection.contractRevisionId !== plan.ticket.contractRevisionId || projection.ruleGraphVersion !== plan.ticket.ruleGraphVersion || typeof projection.identityHash !== "string") return false;
  if (!projection.synthesis || typeof projection.synthesis !== "object" || Array.isArray(projection.synthesis) || Object.keys(projection.synthesis).sort().join("|") !== "dimensionRoles|sharedCause") return false;
  const synthesis = projection.synthesis as Record<string, unknown>;
  if (typeof synthesis.sharedCause !== "string" || !synthesis.sharedCause.trim() || !Array.isArray(synthesis.dimensionRoles) || synthesis.dimensionRoles.length !== 2 || synthesis.dimensionRoles.some((role) => typeof role !== "string" || !role.trim())) return false;
  if (!Array.isArray(projection.dimensions) || !projection.dimensions.length || !Array.isArray(projection.promises) || !Array.isArray(projection.prohibitions)) return false;
  if (!projection.dimensions.every((dimension) => !!dimension && typeof dimension === "object" && !Array.isArray(dimension) && Object.keys(dimension).sort().join("|") === "id|interpretation|observableSignals|prohibitions" && typeof (dimension as Record<string, unknown>).id === "string" && !!((dimension as Record<string, unknown>).id as string).trim() && typeof (dimension as Record<string, unknown>).interpretation === "string" && Array.isArray((dimension as Record<string, unknown>).observableSignals) && Array.isArray((dimension as Record<string, unknown>).prohibitions))) return false;
  const dimensionIds = (projection.dimensions as Array<{ id: string }>).map((dimension) => dimension.id);
  if (new Set(dimensionIds).size !== dimensionIds.length) return false;
  try {
    const { identityHash, ...body } = projection as unknown as AssessmentContractProjection;
    return sameMac(identityHash, assessmentContractIdentity(body));
  } catch { return false; }
}
function validState(value: unknown): value is AssessmentState { if (!value || typeof value !== "object" || Array.isArray(value)) return false; const state = value as Record<string, unknown>; const allowed = ["activationId", "branchId", "canonVersion", "ledgerRevision", "attempt", "consumedTicketIds", "consumedPermitIds", "consumedRepairIds", "existingEvidenceIds", "chapterId", "revisionId", "artifactBindingId", "expectedArtifactDigest"]; if (Object.keys(state).some((key) => !allowed.includes(key))) return false; return typeof state.activationId === "string" && !!state.activationId && typeof state.branchId === "string" && !!state.branchId && typeof state.artifactBindingId === "string" && !!state.artifactBindingId && (state.expectedArtifactDigest === null || typeof state.expectedArtifactDigest === "string" && !!state.expectedArtifactDigest) && Number.isInteger(state.canonVersion) && Number.isInteger(state.ledgerRevision) && Number.isInteger(state.attempt) && [state.consumedTicketIds, state.consumedPermitIds, state.consumedRepairIds, state.existingEvidenceIds].every((list) => Array.isArray(list) && list.every((item) => typeof item === "string")); }
function authenticate(request: AssessExperienceRequest, deps: AssessorDependencies, state: AssessmentState): string | undefined {
  if (!validArtifact(request.artifact)) return "invalid_artifact";
  const plan = request.plan;
  if (!validTrustedRoleBindings(plan.roleBindings)) return "plan_mismatch";
  if (!verifyExperienceStageTicket(plan.ticket, deps) || !Number.isFinite(Date.parse(plan.ticket.expiresAt))) return "ticket_tampered";
  if (Date.parse(plan.ticket.expiresAt) <= deps.now().getTime()) return "ticket_expired";
  const { authorizationMac, ...unsigned } = plan;
  if (!sameMac(authorizationMac, signExperiencePlan(unsigned, deps.ticketSecret))) return "plan_mismatch";
  if (!validAssessmentContract(plan)) return "plan_mismatch";
  if (plan.stage !== plan.ticket.stage || plan.artifactKind !== plan.ticket.artifactKind || plan.artifactKind !== request.artifact.kind || !stageMatches(plan, request.artifact)) return "stage_mismatch";
  if (!stateMatches(plan, state)) return "state_mismatch";
  if (request.artifact.kind !== "blueprint" && (!plan.chapterId || !plan.revisionId || plan.chapterId !== request.artifact.chapterId || plan.revisionId !== request.artifact.revisionId || state.chapterId !== request.artifact.chapterId || state.revisionId !== request.artifact.revisionId)) return "artifact_binding_mismatch";
  if (plan.stage === "rewrite") {
    const authorization = plan.repairAuthorization; if (!authorization || !verifyRepairAuthorization(authorization.token, authorization.expected, deps.ticketSecret, deps.now()) || authorization.tokenDigest !== createHash("sha256").update(canonicalAuthorizationPayload(authorization.token)).digest("hex") || state.consumedRepairIds.includes(authorization.token.repairId)) return "repair_authorization_invalid";
    const token = authorization.token;
    if (plan.ticket.attempt !== token.attempt + 1 || plan.ticket.jobId !== token.jobId || plan.ticket.contractRevisionId !== token.contractRevisionId || plan.ticket.activationId !== token.activationId || plan.ticket.branchId !== token.branchId || plan.ticket.expectedCanonVersion !== token.expectedCanonVersion || plan.ticket.ledgerRevision !== token.ledgerRevision || plan.ticket.ruleGraphVersion !== token.ruleGraphVersion || plan.artifactKind !== token.artifactKind || plan.chapterNumber !== token.chapterNumber || plan.artifactBindingId === token.artifactBindingId || canonicalAuthorizationPayload(plan.roleBindings) !== canonicalAuthorizationPayload(token.roleBindings) || canonicalAuthorizationPayload(plan.repairRuleIds) !== canonicalAuthorizationPayload([...new Set(token.failedRuleIds)].sort()) || (token.artifactKind !== "blueprint" && (plan.chapterId !== token.chapterId || plan.revisionId !== token.revisionId))) return "repair_authorization_invalid";
  } else if (plan.repairAuthorization || plan.repairRuleIds.length) return "repair_authorization_invalid";
  return undefined;
}
function selectedSignals(plan: ExperienceStagePlan): ObservableSignalV2[] | undefined {
  const contract = plan.assessmentContract;
  const map = new Map(contract.dimensions.flatMap((dimension) => dimension.observableSignals.map((signal) => [signal.id, signal] as const)));
  const signals: ObservableSignalV2[] = [];
  for (const dimension of plan.promptProjection.dimensions) {
    const trustedDimension = contract.dimensions.find((item) => item.id === dimension.id); if (!trustedDimension || trustedDimension.interpretation !== dimension.interpretation) return undefined;
    for (const id of dimension.signalIds) { const signal = map.get(id); if (!signal || signal.dimensionId !== dimension.id || signals.some((candidate) => candidate.id === id)) return undefined; signals.push(signal); }
  }
  if (!signals.length || plan.evidenceSchema.length !== signals.length || plan.ruleAdapterIds.some((id) => !isRuleAdapterId(id))) return undefined;
  const expectedAdapters = contract.prohibitions.flatMap((item) => item.ruleAdapterId && isRuleAdapterId(item.ruleAdapterId) ? [item.ruleAdapterId] : []).sort(); if ([...plan.ruleAdapterIds].sort().join("|") !== expectedAdapters.join("|")) return undefined;
  if (canonicalAuthorizationPayload(plan.promptProjection.prohibitions) !== canonicalAuthorizationPayload(contract.prohibitions.map((item) => item.description))) return undefined;
  return plan.evidenceSchema.every((policy, index) => canonicalAuthorizationPayload(policy) === canonicalAuthorizationPayload(signals[index].verification)) ? signals : undefined;
}
const realizationAdapters: GenericRuleAdapterId[] = ["event-negated", "event-intent", "event-failed-attempt", "event-simulation", "event-hearsay", "contains-pasted-label"];
function containingClause(source: string, start: number, end: number): string {
  const boundary = (value: string) => /[\n。！？；.!?;]/u.test(value);
  let clauseStart = start; while (clauseStart > 0 && !boundary(source[clauseStart - 1])) clauseStart -= 1;
  let clauseEnd = end; while (clauseEnd < source.length && !boundary(source[clauseEnd])) clauseEnd += 1;
  return source.slice(clauseStart, clauseEnd < source.length ? clauseEnd + 1 : clauseEnd);
}
function localFinding(source: string, claim: SemanticEvidenceClaim, grounded: GroundedClaim, signal: ObservableSignalV2, roles: ExperienceStagePlan["roleBindings"], configuredAdapters: GenericRuleAdapterId[]): EvidenceFinding | undefined {
  const text = grounded.anchors.map((anchor) => {
    if (signal.verification.kind !== "distribution") return containingClause(source, anchor.start, anchor.end);
    const start = source.lastIndexOf("\n", Math.max(0, anchor.start - 1)) + 1; const next = source.indexOf("\n", anchor.end);
    return source.slice(start, next < 0 ? source.length : next);
  }).join(" "); const slots = claim.slots ?? {};
  const present = (slot: string) => typeof slots[slot as keyof typeof slots] === "string" && (slots[slot as keyof typeof slots] as string).trim() && text.toLocaleLowerCase().includes((slots[slot as keyof typeof slots] as string).toLocaleLowerCase());
  const required: Record<string, string[]> = { mechanic: ["actor", "action", "object", "outcome"], protagonist_action: ["actor", "action", "outcome"], conflict_outcome: ["actor", "action", "opponent", "outcome"], world_reaction: ["actor", "reaction", "outcome"], relationship: ["actor", "action", "counterpart", "reciprocalAction", "relationshipChange"] };
  const policyRequired = signal.verification.kind === "event_slots" ? signal.verification.requiredSlots : [];
  const suppliedEffectSlots = (["feedback", "outcome", "reaction", "reciprocalAction", "relationshipChange"] as RealizationSlot[]).filter((slot) => typeof slots[slot as keyof typeof slots] === "string" && !!slots[slot as keyof typeof slots]?.trim());
  const requiredSlots = unique([...policyRequired, ...(required[signal.kind] ?? []), ...suppliedEffectSlots]) as RealizationSlot[];
  const realization: RealizationBinding = { actor: slots.actor, action: slots.action, object: slots.object, feedback: slots.feedback, outcome: slots.outcome, reaction: slots.reaction, reciprocalAction: slots.reciprocalAction, relationshipChange: slots.relationshipChange, counterpart: slots.counterpart, opponent: slots.opponent, requiredSlots };
  if ([...realizationAdapters, ...configuredAdapters].some((id) => adapterAppliesTo(id, signal.kind) && runRuleAdapter(id, text, realization))) return { ruleId: "evidence.not_realized", severity: "rewrite", dimensionId: signal.dimensionId };
  if (requiredSlots.some((slot) => !present(slot))) return { ruleId: "evidence.required_slot_missing", severity: "rewrite", dimensionId: signal.dimensionId };
  if (["protagonist_action", "conflict_outcome", "mechanic", "relationship"].includes(signal.kind) && (!roles.protagonistId || !roles.aliases.some((alias) => canonicalRoleKey(alias) === canonicalRoleKey(slots.actor ?? "")))) return { ruleId: "evidence.helper_substitution", severity: "rewrite", dimensionId: signal.dimensionId };
  if (signal.kind === "relationship") { const counterpart = roles.counterparts.find((item) => item.id === slots.counterpartId); if (!counterpart || !slots.counterpart || !counterpart.aliases.some((alias) => canonicalRoleKey(alias) === canonicalRoleKey(slots.counterpart!))) return { ruleId: "evidence.counterpart_untrusted", severity: "rewrite", dimensionId: signal.dimensionId }; }
  if (signal.kind === "conflict_outcome") { const opponent = roles.opponents.find((item) => item.id === slots.opponentId); if (!opponent || !slots.opponent || !opponent.aliases.some((alias) => canonicalRoleKey(alias) === canonicalRoleKey(slots.opponent!))) return { ruleId: "evidence.opponent_untrusted", severity: "rewrite", dimensionId: signal.dimensionId }; }
  if (requiredSlots.some((slot) => !Number.isInteger(claim.slotAnchorIndices[slot as keyof typeof claim.slotAnchorIndices]))) return { ruleId: "evidence.slot_anchor_not_grounded", severity: "rewrite", dimensionId: signal.dimensionId };
  if (Object.entries(claim.slotAnchorIndices).some(([slot, index]) => !Number.isInteger(index) || index! < 0 || index! >= grounded.anchors.length || !slots[slot as keyof typeof slots] || !grounded.anchors[index!].text.includes(slots[slot as keyof typeof slots]!))) return { ruleId: "evidence.slot_anchor_not_grounded", severity: "rewrite", dimensionId: signal.dimensionId };
  if (signal.semanticSlots && Object.entries(signal.semanticSlots).some(([name, expected]) => slots[name as keyof typeof slots] !== expected)) return { ruleId: "evidence.binding_mismatch", severity: "rewrite", dimensionId: signal.dimensionId };
  return undefined;
}
function validVerdict(value: unknown): value is { version: 1; claims: SemanticEvidenceClaim[]; sharedCause: { eventId: string; supported: boolean; confidence: number; anchors: Array<{ start: number; end: number; quote: string }>; links: Array<{ dimensionId: string; signalId: string; claimAnchorIndex: number; sharedAnchorIndex: number }> } } {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false; const record = value as Record<string, unknown>;
  if (record.version !== 1 || !Array.isArray(record.claims) || Object.keys(record).some((key) => !["version", "claims", "sharedCause"].includes(key))) return false;
  const shared = record.sharedCause as Record<string, unknown> | undefined; if (!shared || typeof shared.eventId !== "string" || typeof shared.supported !== "boolean" || typeof shared.confidence !== "number" || !Number.isFinite(shared.confidence) || !Array.isArray(shared.anchors) || !Array.isArray(shared.links) || Object.keys(shared).some((key) => !["eventId", "supported", "confidence", "anchors", "links"].includes(key))) return false;
  const anchorValid = (anchor: unknown) => !!anchor && typeof anchor === "object" && !Array.isArray(anchor) && Number.isInteger((anchor as Record<string, unknown>).start) && Number.isInteger((anchor as Record<string, unknown>).end) && typeof (anchor as Record<string, unknown>).quote === "string" && Object.keys(anchor as object).every((key) => ["start", "end", "quote"].includes(key)); if (!shared.anchors.every(anchorValid)) return false;
  if (!shared.links.every((value) => { if (!value || typeof value !== "object" || Array.isArray(value)) return false; const link = value as Record<string, unknown>; return Object.keys(link).sort().join("|") === ["claimAnchorIndex", "dimensionId", "sharedAnchorIndex", "signalId"].sort().join("|") && typeof link.dimensionId === "string" && !!link.dimensionId && typeof link.signalId === "string" && !!link.signalId && Number.isInteger(link.claimAnchorIndex) && Number.isInteger(link.sharedAnchorIndex); })) return false;
  return record.claims.every((value) => { if (!value || typeof value !== "object" || Array.isArray(value)) return false; const claim = value as Record<string, unknown>; if (Object.keys(claim).some((key) => !["version", "eventId", "dimensionId", "signalId", "supported", "confidence", "anchors", "slotAnchorIndices", "slots", "metrics", "distributionAnchorIndices"].includes(key)) || claim.version !== 1 || typeof claim.eventId !== "string" || !claim.eventId || typeof claim.dimensionId !== "string" || typeof claim.signalId !== "string" || typeof claim.supported !== "boolean" || typeof claim.confidence !== "number" || !Number.isFinite(claim.confidence) || !Array.isArray(claim.anchors) || !claim.slotAnchorIndices || typeof claim.slotAnchorIndices !== "object" || Array.isArray(claim.slotAnchorIndices)) return false; if (claim.metrics !== undefined && (!claim.metrics || typeof claim.metrics !== "object" || Array.isArray(claim.metrics) || Object.values(claim.metrics as Record<string, unknown>).some((metric) => typeof metric !== "number" || !Number.isFinite(metric)))) return false; if (claim.distributionAnchorIndices !== undefined && (!claim.distributionAnchorIndices || typeof claim.distributionAnchorIndices !== "object" || Array.isArray(claim.distributionAnchorIndices) || Object.keys(claim.distributionAnchorIndices as Record<string, unknown>).some((key) => !["goal", "pressure", "beat", "turn", "abstraction", "sensory", "rhetoric"].includes(key)) || Object.values(claim.distributionAnchorIndices as Record<string, unknown>).some((indices) => !Array.isArray(indices) || indices.some((index) => !Number.isInteger(index))))) return false; if (claim.slots !== undefined && (!claim.slots || typeof claim.slots !== "object" || Array.isArray(claim.slots) || Object.keys(claim.slots as Record<string, unknown>).some((key) => !["actor", "action", "object", "feedback", "outcome", "reaction", "reciprocalAction", "relationshipChange", "counterpart", "counterpartId", "opponent", "opponentId"].includes(key)) || Object.values(claim.slots as Record<string, unknown>).some((slot) => typeof slot !== "string"))) return false; return claim.anchors.every(anchorValid); });
}
type CheckedVerdict = ReturnType<typeof snapshot> extends infer _ ? { version: 1; claims: SemanticEvidenceClaim[]; sharedCause: { eventId: string; supported: boolean; confidence: number; anchors: Array<{ start: number; end: number; quote: string }>; links: Array<{ dimensionId: string; signalId: string; claimAnchorIndex: number; sharedAnchorIndex: number }> } } : never;
const sameAnchor = (left: { start: number; end: number }, right: { start: number; end: number }): boolean => left.start === right.start && left.end === right.end;
function sharedCauseFinding(source: string, verdict: CheckedVerdict, plan: ExperienceStagePlan, signals: ObservableSignalV2[]): EvidenceFinding | undefined {
  const shared = verdict.sharedCause;
  if (!shared.supported || shared.confidence < .65 || shared.confidence > 1 || !shared.anchors.length || shared.anchors.some((anchor) => anchor.start < 0 || anchor.end > source.length || anchor.end <= anchor.start || source.slice(anchor.start, anchor.end) !== anchor.quote)) return { ruleId: "evidence.shared_cause_unsupported", severity: "rewrite" };
  const expectedDimensions = plan.promptProjection.dimensions.map((dimension) => dimension.id).sort();
  const semanticIds = unique([...expectedDimensions, ...plan.promptProjection.dimensions.flatMap((dimension) => dimension.signalIds), ...plan.duePromiseIds]);
  const substantiveBridge = (quote: string): boolean => {
    if (/(?:信号|承诺|维度|标签|事件\s*(?:id|编号)|令牌)|\b(?:signal|promise|dimension|label|event\s*id|token)s?\b/iu.test(quote)) return false;
    let remainder = quote.normalize("NFKC").toLocaleLowerCase();
    for (const id of [...semanticIds].sort((left, right) => right.length - left.length)) remainder = remainder.split(id.normalize("NFKC").toLocaleLowerCase()).join(" ");
    return remainder.replace(/[^\p{L}\p{N}]+/gu, "").length >= 6;
  };
  if (shared.anchors.some((anchor) => !substantiveBridge(anchor.quote))) return { ruleId: "evidence.shared_cause_unsupported", severity: "rewrite" };
  if (new Set(shared.links.map((link) => `${link.dimensionId}:${link.signalId}:${link.claimAnchorIndex}:${link.sharedAnchorIndex}`)).size !== shared.links.length) return { ruleId: "evidence.shared_cause_unsupported", severity: "rewrite" };
  const linkedClaims: SemanticEvidenceClaim[] = [];
  for (const link of shared.links) {
    const claim = verdict.claims.find((candidate) => candidate.dimensionId === link.dimensionId && candidate.signalId === link.signalId && candidate.eventId === shared.eventId);
    const signal = signals.find((candidate) => candidate.dimensionId === link.dimensionId && candidate.id === link.signalId);
    const claimAnchor = claim?.anchors[link.claimAnchorIndex]; const sharedAnchor = shared.anchors[link.sharedAnchorIndex];
    if (!claim || !signal || !claimAnchor || !sharedAnchor || !sameAnchor(claimAnchor, sharedAnchor) || claimAnchor.quote !== sharedAnchor.quote) return { ruleId: "evidence.shared_cause_unsupported", severity: "rewrite" };
    const linkedIndices = shared.links.filter((candidate) => candidate.dimensionId === link.dimensionId && candidate.signalId === link.signalId).map((candidate) => candidate.claimAnchorIndex);
    if (signal.verification.kind === "distribution") {
      if (!claim.anchors.some((anchor, index) => !linkedIndices.includes(index) && !shared.anchors.some((sharedCandidate) => sameAnchor(anchor, sharedCandidate)))) return { ruleId: "evidence.shared_cause_unsupported", severity: "rewrite" };
    } else {
      const effectSlots: Record<string, string[]> = { mechanic: ["feedback", "outcome"], protagonist_action: ["outcome"], conflict_outcome: ["outcome"], world_reaction: ["reaction", "outcome"], relationship: ["reciprocalAction", "relationshipChange"] };
      const linkedEffect = (effectSlots[signal.kind] ?? []).find((slot) => claim.slotAnchorIndices[slot as keyof typeof claim.slotAnchorIndices] === link.claimAnchorIndex);
      if (!linkedEffect || !claim.slots?.[linkedEffect as keyof NonNullable<SemanticEvidenceClaim["slots"]>] || !claimAnchor.quote.includes(claim.slots[linkedEffect as keyof NonNullable<SemanticEvidenceClaim["slots"]>]!)) return { ruleId: "evidence.shared_cause_unsupported", severity: "rewrite" };
    }
    linkedClaims.push(claim);
  }
  if ([...new Set(shared.links.map((link) => link.dimensionId))].sort().join("|") !== expectedDimensions.join("|") || shared.anchors.some((_, index) => [...new Set(shared.links.filter((link) => link.sharedAnchorIndex === index).map((link) => link.dimensionId))].sort().join("|") !== expectedDimensions.join("|"))) return { ruleId: "evidence.shared_cause_unsupported", severity: "rewrite" };
  for (let left = 0; left < linkedClaims.length; left++) for (let right = left + 1; right < linkedClaims.length; right++) {
    if (linkedClaims[left].dimensionId === linkedClaims[right].dimensionId) continue;
    const a = linkedClaims[left].anchors.map((anchor) => `${anchor.start}:${anchor.end}`).sort(); const b = linkedClaims[right].anchors.map((anchor) => `${anchor.start}:${anchor.end}`).sort();
    if (a.join("|") === b.join("|")) return { ruleId: "evidence.shared_cause_unsupported", severity: "rewrite" };
  }
  return undefined;
}
function sharedAnchorIndexFor(verdict: CheckedVerdict, claim: SemanticEvidenceClaim, claimAnchorIndex: number): number | undefined {
  return verdict.sharedCause.links.find((link) => link.dimensionId === claim.dimensionId && link.signalId === claim.signalId && link.claimAnchorIndex === claimAnchorIndex)?.sharedAnchorIndex;
}
function permit(request: AssessExperienceRequest, artifactHash: string, evidence: ExperienceEvidenceV2[], patch: ExperienceLedgerPatch, deps: AssessorDependencies): ExperiencePublicationPermit {
  const artifact = request.artifact; if (artifact.kind === "blueprint") throw new Error("invalid permit artifact"); const expiresAt = new Date(deps.now().getTime() + (deps.permitTtlMs ?? 600_000)).toISOString();
  const bindings = sortedEvidenceBindings(evidence);
  const context: PublicationPermitContext = { ticketId: request.plan.ticket.id, jobId: request.plan.ticket.jobId, attempt: request.plan.ticket.attempt, contractRevisionId: request.plan.ticket.contractRevisionId, activationId: request.plan.ticket.activationId, branchId: request.plan.ticket.branchId, chapterId: artifact.chapterId, revisionId: artifact.revisionId, artifactBindingId: request.plan.artifactBindingId, artifactHash, stage: request.plan.stage, artifactKind: request.plan.artifactKind, ruleGraphVersion: request.plan.ticket.ruleGraphVersion, expectedCanonVersion: request.plan.ticket.expectedCanonVersion, ledgerRevision: request.plan.ticket.ledgerRevision, evidenceIds: bindings.map((binding) => binding.evidenceId).sort(), evidenceBindings: bindings.map((binding) => ({ ...binding })), evidenceRootHash: evidenceRootHash(bindings), ledgerPatchHash: ledgerPatchHash(patch) };
  const permitId = `permit_${createHash("sha256").update(canonicalAuthorizationPayload({ ticketId: request.plan.ticket.id, artifactHash, evidenceRootHash: context.evidenceRootHash, expiresAt })).digest("base64url")}`;
  return issuePublicationPermit(context, permitId, expiresAt, deps.ticketSecret);
}
export async function consumePublicationPermit(value: unknown, context: PublicationPermitContext, deps: AssessorDependencies): Promise<boolean> { try { if (!verifyPermit(value, context, deps.ticketSecret, deps.now())) return false; const permit = value as ExperiencePublicationPermit; const state = await deps.statePort.read({ ticketId: permit.ticketId, jobId: permit.jobId }); if (!validState(state) || state.consumedPermitIds.includes(permit.permitId) || !state.consumedTicketIds.includes(permit.ticketId) || state.activationId !== permit.activationId || state.branchId !== permit.branchId || state.canonVersion !== permit.expectedCanonVersion || state.ledgerRevision !== permit.ledgerRevision || state.attempt !== permit.attempt || state.chapterId !== permit.chapterId || state.revisionId !== permit.revisionId || state.artifactBindingId !== permit.artifactBindingId || state.expectedArtifactDigest !== permit.artifactHash) return false; return !!await deps.statePort.consumePermit({ permitId: permit.permitId, ticketId: permit.ticketId, permitDigest: publicationPermitDigest(permit), context: structuredClone(context), expected: { activationId: permit.activationId, branchId: permit.branchId, canonVersion: permit.expectedCanonVersion, ledgerRevision: permit.ledgerRevision, attempt: permit.attempt, chapterId: permit.chapterId, revisionId: permit.revisionId, artifactBindingId: permit.artifactBindingId, expectedArtifactDigest: permit.artifactHash } }); } catch { return false; } }
function repair(request: AssessExperienceRequest, ids: string[], deps: AssessorDependencies): ExperienceRepairToken { const artifact = request.artifact; const expiresAt = new Date(deps.now().getTime() + (deps.repairTtlMs ?? 300_000)).toISOString(); const unsigned = { version: 1 as const, repairId: `repair_${createHash("sha256").update(`${request.plan.ticket.id}\u001f${artifactHashSafe(request)}\u001f${expiresAt}`).digest("base64url")}`, ticketId: request.plan.ticket.id, jobId: request.plan.ticket.jobId, attempt: request.plan.ticket.attempt, contractRevisionId: request.plan.ticket.contractRevisionId, activationId: request.plan.ticket.activationId, branchId: request.plan.ticket.branchId, stage: request.plan.stage, artifactKind: request.plan.artifactKind, ruleGraphVersion: request.plan.ticket.ruleGraphVersion, expectedCanonVersion: request.plan.ticket.expectedCanonVersion, ledgerRevision: request.plan.ticket.ledgerRevision, chapterNumber: request.plan.chapterNumber, ...(artifact.kind === "blueprint" ? {} : { chapterId: artifact.chapterId, revisionId: artifact.revisionId }), artifactBindingId: request.plan.artifactBindingId, roleBindings: structuredClone(request.plan.roleBindings), artifactHash: artifactHashSafe(request), failedRuleIds: unique(ids), expiresAt }; return { ...unsigned, signature: sign(repairDomain, unsigned, deps.ticketSecret) }; }
export function verifyRepairToken(value: unknown, context: RepairTokenContext, secret: string, now: Date): boolean { return !!value && typeof value === "object" && !Array.isArray(value) && verifyRepairAuthorization(value as ExperienceRepairToken, context, secret, now); }
function rewrite(request: AssessExperienceRequest, findings: EvidenceFinding[], deps: AssessorDependencies): ExperienceOperationResult<ExperienceAssessment> { const blocking = findings.find((finding) => finding.severity === "rejected"); if (blocking) return failure(request, blocking.ruleId); const ids = unique(findings.map((finding) => finding.ruleId)); return { ok: true, value: { status: "rewrite", artifactKind: request.artifact.kind, failedRuleIds: ids, repairToken: repair(request, ids, deps), message: "Evidence must be grounded in the submitted artifact." } }; }
function casInput(request: AssessExperienceRequest, state: AssessmentState, artifactHash: string, outcomeId: string, outcome: "accepted" | "rewrite" | "rejected" | "blueprint", newEvidenceIds: readonly string[] = [], issuedAuthorization?: NonNullable<Parameters<AssessorDependencies["statePort"]["consumeTicket"]>[0]["issuedAuthorization"]>): Parameters<AssessorDependencies["statePort"]["consumeTicket"]>[0] { const repairAuthorization = request.plan.repairAuthorization; return { ticketId: request.plan.ticket.id, artifactHash, outcomeId, outcome, newEvidenceIds: [...newEvidenceIds].sort(), ...(issuedAuthorization ? { issuedAuthorization: structuredClone(issuedAuthorization) } : {}), ...(repairAuthorization ? { repairAuthorization: { repairId: repairAuthorization.token.repairId, tokenDigest: repairAuthorization.tokenDigest, expected: structuredClone(repairAuthorization.expected) } } : {}), expected: { activationId: request.plan.ticket.activationId, branchId: request.plan.ticket.branchId, canonVersion: request.plan.ticket.expectedCanonVersion, ledgerRevision: request.plan.ticket.ledgerRevision, attempt: request.plan.ticket.attempt, ...(request.plan.chapterId ? { chapterId: request.plan.chapterId } : {}), ...(request.plan.revisionId ? { revisionId: request.plan.revisionId } : {}), artifactBindingId: request.plan.artifactBindingId, expectedArtifactDigest: artifactHash, existingEvidenceIds: [...state.existingEvidenceIds].sort() } }; }
async function consumeTicketSafely(consume: AssessorDependencies["statePort"]["consumeTicket"], input: Parameters<AssessorDependencies["statePort"]["consumeTicket"]>[0]): Promise<boolean> { try { return !!await consume(input); } catch { return false; } }
async function issueRewrite(request: AssessExperienceRequest, findings: EvidenceFinding[], deps: AssessorDependencies, consume: AssessorDependencies["statePort"]["consumeTicket"], state: AssessmentState, artifactHash: string): Promise<ExperienceOperationResult<ExperienceAssessment>> { const result = rewrite(request, findings, deps); let outcomeId = `blocked_${findings.map((finding) => finding.ruleId).join("_")}`; let outcome: "rewrite" | "rejected" = "rejected"; let issuedAuthorization: NonNullable<Parameters<AssessorDependencies["statePort"]["consumeTicket"]>[0]["issuedAuthorization"]> | undefined; if (result.ok && result.value.status === "rewrite") { const token = result.value.repairToken; outcomeId = token.repairId; outcome = "rewrite"; issuedAuthorization = { kind: "repair", repairId: token.repairId, tokenDigest: createHash("sha256").update(canonicalAuthorizationPayload(token)).digest("hex"), context: repairContext(token) }; } if (!await consumeTicketSafely(consume, casInput(request, state, artifactHash, outcomeId, outcome, [], issuedAuthorization))) return failure(request, "ticket_reused"); return result; }
function validBlueprint(value: Record<string, unknown>, plan: ExperienceStagePlan): boolean {
  const allowed = ["axisSignalIds", "chapters", "endingContract", "hardPromiseIds", "meta", "protagonist", "schemaVersion", "sharedCause", "title"];
  if (Object.keys(value).some((key) => !allowed.includes(key))) return false;
  const exactObject = (candidate: unknown, allowedKeys: readonly string[], requiredKeys: readonly string[] = allowedKeys): candidate is Record<string, unknown> => !!candidate && typeof candidate === "object" && !Array.isArray(candidate) && Object.getPrototypeOf(candidate) === Object.prototype && Object.keys(candidate).every((key) => allowedKeys.includes(key)) && requiredKeys.every((key) => Object.hasOwn(candidate, key));
  if (!exactObject(value.protagonist, ["id"]) || !exactObject(value.endingContract, ["target", "cost"], ["target"]) || !exactObject(value.sharedCause, ["event", "dimensionIds"]) || value.meta !== undefined && !exactObject(value.meta, ["prohibitionsSatisfied"])) return false;
  const protagonist = value.protagonist; const ending = value.endingContract; const shared = value.sharedCause;
  if (value.meta !== undefined && value.meta.prohibitionsSatisfied !== true) return false;
  const expectedSignals = plan.promptProjection.dimensions.flatMap((dimension) => dimension.signalIds).sort(); const suppliedSignals = Array.isArray(value.axisSignalIds) ? value.axisSignalIds : [];
  const expectedPromises = [...plan.hardPresencePromiseIds].sort(); const suppliedPromises = Array.isArray(value.hardPromiseIds) ? value.hardPromiseIds : [];
  if (value.schemaVersion !== 1 || typeof value.title !== "string" || !value.title.trim() || !protagonist || typeof protagonist.id !== "string" || !protagonist.id || protagonist.id !== plan.roleBindings.protagonistId || !ending || typeof ending.target !== "string" || !ending.target.trim() || (ending.cost !== undefined && typeof ending.cost !== "string")) return false;
  if (suppliedSignals.some((id) => typeof id !== "string") || [...suppliedSignals].sort().join("|") !== expectedSignals.join("|") || suppliedPromises.some((id) => typeof id !== "string") || [...suppliedPromises].sort().join("|") !== expectedPromises.join("|")) return false;
  const expectedDimensions = plan.promptProjection.dimensions.map((dimension) => dimension.id).sort();
  if (!shared || typeof shared.event !== "string" || !shared.event.trim() || !Array.isArray(shared.dimensionIds) || [...shared.dimensionIds].sort().join("|") !== expectedDimensions.join("|")) return false;
  if (!Array.isArray(value.chapters) || !value.chapters.length) return false;
  return value.chapters.every((chapter) => { if (!chapter || typeof chapter !== "object" || Array.isArray(chapter)) return false; const record = chapter as Record<string, unknown>; if (Object.keys(record).some((key) => !["number", "signalIds", "promiseIds", "event", "cause", "outcome", "cost"].includes(key))) return false; return Number.isInteger(record.number) && Array.isArray(record.signalIds) && record.signalIds.every((id) => typeof id === "string") && Array.isArray(record.promiseIds) && record.promiseIds.every((id) => typeof id === "string") && [record.event, record.cause, record.outcome, record.cost].every((field) => typeof field === "string" && !!field.trim()); });
}
function blueprintPointer(root: unknown, pointer: string): unknown {
  if (pointer === "") return root; if (!pointer.startsWith("/")) return undefined;
  let current: unknown = root;
  for (const raw of pointer.slice(1).split("/")) {
    const key = raw.replace(/~1/g, "/").replace(/~0/g, "~");
    if (Array.isArray(current)) { if (!/^(?:0|[1-9]\d*)$/.test(key)) return undefined; current = current[Number(key)]; }
    else if (current && typeof current === "object" && Object.hasOwn(current, key)) current = (current as Record<string, unknown>)[key];
    else return undefined;
  }
  return current;
}
function validBlueprintVerdict(value: unknown): value is SemanticBlueprintVerdict {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false; const verdict = value as Record<string, unknown>;
  if (Object.keys(verdict).sort().join("|") !== ["confidence", "ending", "kind", "promises", "sharedCause", "signals", "version"].sort().join("|") || verdict.version !== 1 || verdict.kind !== "blueprint" || typeof verdict.confidence !== "number" || !Number.isFinite(verdict.confidence) || verdict.confidence < 0 || verdict.confidence > 1 || !Array.isArray(verdict.signals) || !Array.isArray(verdict.promises)) return false;
  const exact = (item: unknown, keys: string[]): item is Record<string, unknown> => !!item && typeof item === "object" && !Array.isArray(item) && Object.keys(item).sort().join("|") === [...keys].sort().join("|");
  if (!verdict.signals.every((item) => exact(item, ["dimensionId", "signalId", "pointer", "supported"]) && typeof item.dimensionId === "string" && typeof item.signalId === "string" && typeof item.pointer === "string" && typeof item.supported === "boolean")) return false;
  if (!verdict.promises.every((item) => exact(item, ["promiseId", "pointer", "supported"]) && typeof item.promiseId === "string" && typeof item.pointer === "string" && typeof item.supported === "boolean")) return false;
  const ending = verdict.ending; const shared = verdict.sharedCause;
  return exact(ending, ["targetPointer", "costPointer", "supported", "systemState", "protagonistOutcome", "hasRealCost"]) && typeof ending.targetPointer === "string" && typeof ending.costPointer === "string" && typeof ending.supported === "boolean" && ["available", "unavailable", "not_applicable"].includes(ending.systemState as string) && ["fulfilled", "defeated", "unresolved"].includes(ending.protagonistOutcome as string) && typeof ending.hasRealCost === "boolean" && exact(shared, ["pointer", "dimensionIds", "supported"]) && typeof shared.pointer === "string" && Array.isArray(shared.dimensionIds) && shared.dimensionIds.every((id) => typeof id === "string") && typeof shared.supported === "boolean";
}
function validateBlueprintSemantics(value: Record<string, unknown>, verdict: SemanticBlueprintVerdict, plan: ExperienceStagePlan, signals: ObservableSignalV2[]): EvidenceFinding | undefined {
  if (verdict.confidence < .65) return { ruleId: "blueprint.confidence_insufficient", severity: "rewrite" };
  const ids = unique([...plan.promptProjection.dimensions.flatMap((dimension) => [dimension.id, ...dimension.signalIds]), ...plan.hardPresencePromiseIds]);
  const substantive = (candidate: unknown): candidate is string => {
    if (typeof candidate !== "string" || candidate.trim().length < 8) return false;
    if (/(?:本章|信号|承诺|维度|标签|读者|作者|体验词)|\b(?:chapter|signal|promise|dimension|label|reader|author|descriptor)s?\b/iu.test(candidate)) return false;
    let remainder = candidate.normalize("NFKC").toLocaleLowerCase();
    for (const id of [...ids].sort((left, right) => right.length - left.length)) remainder = remainder.split(id.normalize("NFKC").toLocaleLowerCase()).join(" ");
    for (const description of signals.map((signal) => signal.description.normalize("NFKC").toLocaleLowerCase().trim()).filter((text) => text.length >= 4).sort((left, right) => right.length - left.length)) remainder = remainder.split(description).join(" ");
    return remainder.replace(/[^\p{L}\p{N}]+/gu, "").length >= 6;
  };
  const chapterAt = (pointer: string): Record<string, unknown> | undefined => {
    const match = /^\/chapters\/(0|[1-9]\d*)\/event$/.exec(pointer); if (!match) return undefined;
    const chapter = (value.chapters as unknown[])[Number(match[1])]; return chapter && typeof chapter === "object" && !Array.isArray(chapter) ? chapter as Record<string, unknown> : undefined;
  };
  const expectedSignals = plan.promptProjection.dimensions.flatMap((dimension) => dimension.signalIds.map((signalId) => `${dimension.id}:${signalId}`)).sort();
  const suppliedSignals = verdict.signals.map((item) => `${item.dimensionId}:${item.signalId}`).sort();
  if (new Set(suppliedSignals).size !== suppliedSignals.length || suppliedSignals.join("|") !== expectedSignals.join("|") || verdict.signals.some((item) => { const chapter = chapterAt(item.pointer); return !item.supported || !chapter || !substantive(blueprintPointer(value, item.pointer)) || !Array.isArray(chapter.signalIds) || !chapter.signalIds.includes(item.signalId); })) return { ruleId: "blueprint.signal_unsupported", severity: "rewrite" };
  const expectedPromises = [...plan.hardPresencePromiseIds].sort(); const suppliedPromises = verdict.promises.map((item) => item.promiseId).sort();
  if (new Set(suppliedPromises).size !== suppliedPromises.length || suppliedPromises.join("|") !== expectedPromises.join("|") || verdict.promises.some((item) => { const chapter = chapterAt(item.pointer); return !item.supported || !chapter || !substantive(blueprintPointer(value, item.pointer)) || !Array.isArray(chapter.promiseIds) || !chapter.promiseIds.includes(item.promiseId); })) return { ruleId: "blueprint.promise_unsupported", severity: "rewrite" };
  const target = blueprintPointer(value, verdict.ending.targetPointer); const cost = blueprintPointer(value, verdict.ending.costPointer);
  const canonicalEnding = value.endingContract as Record<string, unknown>; const canonicalShared = value.sharedCause as Record<string, unknown>; const chapters = value.chapters as Array<Record<string, unknown>>;
  const canonicalTarget = canonicalEnding.target; const canonicalCost = canonicalEnding.cost;
  const mechanicGuarantee = plan.ruleAdapterIds.includes("curated-mechanic-unavailable"); const outcomeGuarantee = plan.ruleAdapterIds.includes("curated-outcome-weakened");
  const canonicalNarrative = [canonicalTarget, canonicalCost, canonicalShared.event, ...chapters.flatMap((chapter) => [chapter.event, chapter.outcome, chapter.cost, chapter.cause])].filter((item): item is string => typeof item === "string");
  const violatedGuarantee = plan.ruleAdapterIds.some((id) => (id === "curated-mechanic-unavailable" || id === "curated-outcome-weakened") && canonicalNarrative.some((field) => runRuleAdapter(id, field)));
  if (!verdict.ending.supported || !substantive(canonicalTarget) || !substantive(target) || (mechanicGuarantee && verdict.ending.systemState !== "available") || (outcomeGuarantee && verdict.ending.protagonistOutcome !== "fulfilled") || verdict.ending.hasRealCost && (!substantive(canonicalCost) || !substantive(cost) || verdict.ending.targetPointer === verdict.ending.costPointer) || violatedGuarantee) return { ruleId: "blueprint.ending_unsupported", severity: "rewrite" };
  const expectedDimensions = plan.promptProjection.dimensions.map((dimension) => dimension.id).sort(); const shared = blueprintPointer(value, verdict.sharedCause.pointer);
  const sharedChapter = chapterAt(verdict.sharedCause.pointer); const linkedDimensions = verdict.signals.filter((item) => item.pointer === verdict.sharedCause.pointer).map((item) => item.dimensionId);
  if (!verdict.sharedCause.supported || !sharedChapter || !substantive(canonicalShared.event) || !substantive(shared) || [...verdict.sharedCause.dimensionIds].sort().join("|") !== expectedDimensions.join("|") || [...new Set(linkedDimensions)].sort().join("|") !== expectedDimensions.join("|")) return { ruleId: "blueprint.shared_cause_unsupported", severity: "rewrite" };
  return undefined;
}
function patch(request: AssessExperienceRequest, signals: ObservableSignalV2[], evidence: ReturnType<typeof evidenceFromClaim>[], contract: AssessmentContractProjection): { patch: ExperienceLedgerPatch; candidates: CanonFactCandidateV2[]; missingPromises: string[] } {
  const deliveredSignalIdsByDimension = Object.fromEntries(request.plan.promptProjection.dimensions.map((dimension) => [dimension.id, evidence.filter((item) => item.dimensionId === dimension.id).map((item) => item.signalId)]));
  const candidates = evidence.flatMap((item) => { const signal = signals.find((candidate) => candidate.id === item.signalId)!; if (!(["cross_chapter", "whole_story"] as string[]).includes(signal.persistence) || !(item.observation.outcome || item.observation.relationshipOrStateChange)) return []; const kind: CanonFactCandidateV2["kind"] = signal.kind === "mechanic" ? "mechanic" : signal.kind === "relationship" ? "relationship" : "outcome"; const unsigned = cleanAuthorizationValue({ evidenceId: item.id, revisionId: item.chapterRevisionId, dimensionId: item.dimensionId, signalId: item.signalId, kind, observation: structuredClone(item.observation), anchors: item.anchors.map((anchor) => ({ ...anchor })) }); return [{ id: canonFactCandidateId(unsigned), ...unsigned }]; });
  const persistentResultsByDimension = Object.fromEntries(request.plan.promptProjection.dimensions.map((dimension) => [dimension.id, candidates.filter((candidate) => candidate.dimensionId === dimension.id).map(({ id, revisionId, kind }) => ({ id, revisionId, kind }))]));
  const promiseEvidenceLinks: Record<string, Record<string, string[]>> = {}; const missingPromises: string[] = [];
  for (const promiseId of request.plan.duePromiseIds) {
    const promise = contract.promises.find((item) => item.id === promiseId);
    if (!promise) { missingPromises.push(promiseId); continue; }
    const dimensions = promise.dimensionId === "both" ? contract.dimensions.map((dimension) => dimension.id) : [promise.dimensionId];
    const links: Record<string, string[]> = {};
    let complete = true;
    for (const dimensionId of dimensions) {
      const relevant = evidence.filter((item) => item.dimensionId === dimensionId);
      if (new Set(relevant.map((item) => item.signalId)).size < promise.minimumSignals) { complete = false; break; }
      links[dimensionId] = relevant.map((item) => item.id).sort();
    }
    if (!complete) missingPromises.push(promiseId); else promiseEvidenceLinks[promiseId] = links;
  }
  const newDebtsByDimension = Object.fromEntries(request.plan.promptProjection.dimensions.map((dimension) => [dimension.id, request.plan.newDebts.filter((debt) => debt.dimensionId === dimension.id).map(({ promiseId, dueByChapter }) => ({ promiseId, dueByChapter }))]));
  return { patch: { ticket: { ...request.plan.ticket }, expectedRevision: request.plan.ticket.ledgerRevision, nextRevision: request.plan.ticket.ledgerRevision + 1, contractRevisionId: request.plan.ticket.contractRevisionId, activationId: request.plan.ticket.activationId, branchId: request.plan.ticket.branchId, expectedCanonVersion: request.plan.ticket.expectedCanonVersion, chapterNumber: request.plan.chapterNumber, deliveredSignalIdsByDimension, persistentResultsByDimension, newDebtsByDimension, deliveredPromiseIds: Object.keys(promiseEvidenceLinks), evidenceIds: evidence.map((item) => item.id), canonFactCandidates: candidates.map((candidate) => structuredClone(candidate)), promiseEvidenceLinks }, candidates, missingPromises };
}

export async function assessExperience(input: AssessExperienceRequest, inputDeps: AssessorDependencies): Promise<ExperienceOperationResult<ExperienceAssessment>> {
  const ticketSecret = `${inputDeps.ticketSecret}`; const now = inputDeps.now.bind(inputDeps); const judge = inputDeps.semanticJudgePort?.judge?.bind(inputDeps.semanticJudgePort); const judgeTimeoutMs = inputDeps.judgeTimeoutMs ?? 15_000;
  const request = snapshot(input); if (!request || !validArtifact(request.artifact)) return failure(input, "invalid_artifact");
  const deps = { ...inputDeps, ticketSecret, now }; const read = inputDeps.statePort?.read?.bind(inputDeps.statePort); const consumeTicket = inputDeps.statePort?.consumeTicket?.bind(inputDeps.statePort); const bindArtifact = inputDeps.statePort?.bindArtifactDigest?.bind(inputDeps.statePort); if (!read || !consumeTicket || !judge) return failure(request, "state_unavailable");
  let before: AssessmentState; try { const value = snapshot(await read({ ticketId: request.plan.ticket.id, jobId: request.plan.ticket.jobId })); if (!validState(value)) return failure(request, "state_unavailable"); before = freeze(value); } catch { return failure(request, "state_unavailable"); }
  let auth: string | undefined; try { auth = authenticate(request, deps, before); } catch { return failure(request, "plan_mismatch"); } if (auth) return failure(request, auth); const contract = request.plan.assessmentContract; const signals = selectedSignals(request.plan); if (!signals) return failure(request, "plan_mismatch");
  let source: string; let artifactHash: string; try { source = sourceForArtifact(request.artifact); artifactHash = hashArtifact(request.artifact); } catch { return failure(request, "invalid_artifact"); }
  if (request.plan.expectedArtifactDigest && request.plan.expectedArtifactDigest !== artifactHash) return failure(request, "artifact_digest_mismatch");
  if (before.expectedArtifactDigest === null) {
    if (!bindArtifact) return failure(request, "state_unavailable");
    let bound = false; try { bound = !!await bindArtifact({ ticketId: request.plan.ticket.id, artifactBindingId: request.plan.artifactBindingId, artifactHash, expected: { activationId: request.plan.ticket.activationId, branchId: request.plan.ticket.branchId, canonVersion: request.plan.ticket.expectedCanonVersion, ledgerRevision: request.plan.ticket.ledgerRevision, attempt: request.plan.ticket.attempt, ...(request.plan.chapterId ? { chapterId: request.plan.chapterId } : {}), ...(request.plan.revisionId ? { revisionId: request.plan.revisionId } : {}), expectedArtifactDigest: null } }); } catch { return failure(request, "state_unavailable"); }
    if (!bound) return failure(request, "artifact_binding_conflict");
    let rebound: AssessmentState; try { const value = snapshot(await read({ ticketId: request.plan.ticket.id, jobId: request.plan.ticket.jobId })); if (!validState(value)) return failure(request, "state_unavailable"); rebound = freeze(value); } catch { return failure(request, "state_unavailable"); }
    if (!stateMatches(request.plan, rebound) || rebound.expectedArtifactDigest !== artifactHash || canonicalAuthorizationPayload({ ...before, expectedArtifactDigest: artifactHash }) !== canonicalAuthorizationPayload(rebound)) return failure(request, "state_changed");
    before = rebound;
  } else if (before.expectedArtifactDigest !== artifactHash) return failure(request, "artifact_digest_mismatch");
  if (request.artifact.kind === "blueprint") {
    const blueprint = request.artifact.value as Record<string, unknown>;
    if (!validBlueprint(blueprint, request.plan)) return issueRewrite(request, [{ ruleId: "blueprint.invalid_manifest", severity: "rewrite" }], deps, consumeTicket, before, artifactHash);
    const blueprintCase = freeze(snapshot({ version: 1 as const, contractRevisionId: contract.contractRevisionId, stage: request.plan.stage, artifactKind: request.artifact.kind, source, sourceHash: artifactHash, synthesis: snapshot(contract.synthesis)!, signals: signals.map((signal) => { const dimension = contract.dimensions.find((item) => item.id === signal.dimensionId)!; const projection = request.plan.promptProjection.dimensions.find((item) => item.id === signal.dimensionId)!; return { dimensionId: signal.dimensionId, signalId: signal.id, kind: signal.kind, interpretation: dimension.interpretation, description: signal.description, semanticSlots: signal.semanticSlots ? { ...signal.semanticSlots } : undefined, policy: snapshot(signal.verification)!, canonFactReferences: projection.factReferences.map((fact) => ({ ...fact })), prohibitions: [...dimension.prohibitions, ...contract.prohibitions.filter((item) => item.dimensionId === "both")].map(({ id, kind, description, severity, ruleAdapterId }) => ({ id, kind, description, severity, ...(ruleAdapterId ? { ruleAdapterId } : {}) })) }; }) }))!;
    let blueprintResult: unknown; const blueprintController = new AbortController(); let blueprintTimer: ReturnType<typeof setTimeout> | undefined;
    try { const deadline = new Promise<never>((_, reject) => { blueprintTimer = setTimeout(() => { blueprintController.abort(); reject(new Error("timeout")); }, judgeTimeoutMs); }); blueprintResult = await Promise.race([judge(blueprintCase, { signal: blueprintController.signal }), deadline]); }
    catch { return unavailable(request.plan.ticket.jobId); } finally { if (blueprintTimer) clearTimeout(blueprintTimer); }
    blueprintResult = snapshot(blueprintResult); if (!validBlueprintVerdict(blueprintResult)) return invalidModel(request.plan.ticket.jobId); freeze(blueprintResult);
    const blueprintFinding = validateBlueprintSemantics(blueprint, blueprintResult, request.plan, signals); if (blueprintFinding) return issueRewrite(request, [blueprintFinding], deps, consumeTicket, before, artifactHash);
    let current: AssessmentState; try { const value = snapshot(await read({ ticketId: request.plan.ticket.id, jobId: request.plan.ticket.jobId })); if (!validState(value)) return failure(request, "state_unavailable"); current = freeze(value); } catch { return failure(request, "state_unavailable"); }
    if (!stateMatches(request.plan, current) || canonicalAuthorizationPayload(before) !== canonicalAuthorizationPayload(current)) return failure(request, "state_changed");
    if (!await consumeTicketSafely(consumeTicket, casInput(request, current, artifactHash, `blueprint_${artifactHash}`, "blueprint"))) return failure(request, "ticket_reused");
    return { ok: true, value: { status: "accepted", artifactKind: "blueprint", artifactHash } };
  }
  const allProhibitions = [...contract.prohibitions, ...contract.dimensions.flatMap((dimension) => dimension.prohibitions)]; const unknownAdapter = allProhibitions.find((prohibition) => prohibition.ruleAdapterId && !isRuleAdapterId(prohibition.ruleAdapterId)); if (unknownAdapter) return failure(request, "plan_mismatch");
  const globalAdapterFinding = request.plan.ruleAdapterIds.find((id) => (id === "curated-mechanic-unavailable" || id === "curated-outcome-weakened") && signals.some((signal) => adapterAppliesTo(id, signal.kind)) && runRuleAdapter(id, source));
  if (globalAdapterFinding) return issueRewrite(request, [{ ruleId: `prohibition.${globalAdapterFinding}`, severity: "rewrite" }], deps, consumeTicket, before, artifactHash);
  const judgeCase = freeze(snapshot({ version: 1 as const, contractRevisionId: contract.contractRevisionId, stage: request.plan.stage, artifactKind: request.artifact.kind, source, sourceHash: artifactHash, synthesis: snapshot(contract.synthesis)!, signals: signals.map((signal) => { const dimension = contract.dimensions.find((item) => item.id === signal.dimensionId)!; const projection = request.plan.promptProjection.dimensions.find((item) => item.id === signal.dimensionId)!; return { dimensionId: signal.dimensionId, signalId: signal.id, kind: signal.kind, interpretation: dimension.interpretation, description: signal.description, semanticSlots: signal.semanticSlots ? { ...signal.semanticSlots } : undefined, policy: snapshot(signal.verification)!, canonFactReferences: projection.factReferences.map((fact) => ({ ...fact })), prohibitions: [...dimension.prohibitions, ...contract.prohibitions.filter((item) => item.dimensionId === "both")].map(({ id, kind, description, severity, ruleAdapterId }) => ({ id, kind, description, severity, ...(ruleAdapterId ? { ruleAdapterId } : {}) })) }; }) }))!;
  let verdict: unknown; const controller = new AbortController(); let timer: ReturnType<typeof setTimeout> | undefined; try { const deadline = new Promise<never>((_, reject) => { timer = setTimeout(() => { controller.abort(); reject(new Error("timeout")); }, judgeTimeoutMs); }); verdict = await Promise.race([judge(judgeCase, { signal: controller.signal }), deadline]); } catch { return unavailable(request.plan.ticket.jobId); } finally { if (timer) clearTimeout(timer); }
  verdict = snapshot(verdict); if (!validVerdict(verdict)) return invalidModel(request.plan.ticket.jobId); freeze(verdict);
  const sharedFinding = sharedCauseFinding(source, verdict, request.plan, signals); if (sharedFinding) return issueRewrite(request, [sharedFinding], deps, consumeTicket, before, artifactHash);
  let after: AssessmentState; try { const value = snapshot(await read({ ticketId: request.plan.ticket.id, jobId: request.plan.ticket.jobId })); if (!validState(value)) return failure(request, "state_unavailable"); after = freeze(value); } catch { return failure(request, "state_unavailable"); } if (!stateMatches(request.plan, after) || canonicalAuthorizationPayload(before) !== canonicalAuthorizationPayload(after)) return failure(request, "state_changed");
  const artifact = request.artifact;
  const bodyStart = artifact.title.length + 1;
  const claims = verdict.claims; if (claims.length !== signals.length || new Set(claims.map((claim) => `${claim.dimensionId}:${claim.signalId}`)).size !== claims.length) return invalidModel(request.plan.ticket.jobId);
  const findings: EvidenceFinding[] = []; const grounded: Array<{ signal: ObservableSignalV2; value: GroundedClaim }> = []; const spans: Array<{ dimensionId: string; signalId: string; start: number; end: number; sharedAnchorIndex?: number }> = [];
  for (const claim of claims) { const signal = signals.find((candidate) => candidate.id === claim.signalId && candidate.dimensionId === claim.dimensionId); if (!signal) return invalidModel(request.plan.ticket.jobId); if (!claim.supported || claim.confidence < .65) { findings.push({ ruleId: "evidence.judge_unsupported", severity: "rewrite" }); continue; } const value = groundClaim(source, claim, signal, { bodyStart }); if ("ruleId" in value) { if (value.ruleId === "invalid_model_output") return invalidModel(request.plan.ticket.jobId); findings.push(value); continue; } const configuredAdapters = allProhibitions.filter((prohibition) => (prohibition.dimensionId === "both" || prohibition.dimensionId === signal.dimensionId) && prohibition.ruleAdapterId && isRuleAdapterId(prohibition.ruleAdapterId)).map((prohibition) => prohibition.ruleAdapterId as GenericRuleAdapterId); const local = localFinding(source, claim, value, signal, request.plan.roleBindings, configuredAdapters); if (local) { findings.push(local); continue; } for (const [anchorIndex, anchor] of value.anchors.entries()) { const sharedAnchorIndex = sharedAnchorIndexFor(verdict, claim, anchorIndex); const collision = spans.find((span) => anchor.start < span.end && span.start < anchor.end && !(span.dimensionId !== signal.dimensionId && span.start === anchor.start && span.end === anchor.end && span.sharedAnchorIndex !== undefined && span.sharedAnchorIndex === sharedAnchorIndex)); if (collision) findings.push({ ruleId: "evidence.double_counted_span", severity: "rewrite" }); spans.push({ dimensionId: signal.dimensionId, signalId: signal.id, start: anchor.start, end: anchor.end, ...(sharedAnchorIndex !== undefined ? { sharedAnchorIndex } : {}) }); } grounded.push({ signal, value }); }
  if (findings.length) return issueRewrite(request, findings, deps, consumeTicket, after, artifactHash);
  const evidence = grounded.map(({ signal, value }) => evidenceFromClaim({ id: createHash("sha256").update(canonicalAuthorizationPayload([request.plan.ticket.id, request.plan.ticket.jobId, request.plan.ticket.attempt, request.plan.ticket.contractRevisionId, request.plan.ticket.activationId, request.plan.ticket.branchId, request.plan.stage, artifact.kind, artifact.chapterId, artifact.revisionId, artifactHash, signal.dimensionId, signal.id, value.claim.eventId])).digest("base64url"), contractRevisionId: request.plan.ticket.contractRevisionId, activationId: request.plan.ticket.activationId, branchId: request.plan.ticket.branchId, chapterId: artifact.chapterId, revisionId: artifact.revisionId, sourceHash: artifactHash, ticketId: request.plan.ticket.id, jobId: request.plan.ticket.jobId, attempt: request.plan.ticket.attempt, stage: request.plan.stage, artifactKind: artifact.kind, ruleGraphVersion: request.plan.ticket.ruleGraphVersion, expectedCanonVersion: request.plan.ticket.expectedCanonVersion, ledgerRevision: request.plan.ticket.ledgerRevision, grounded: value }));
  if (new Set(evidence.map((item) => item.id)).size !== evidence.length || evidence.some((item) => before.existingEvidenceIds.includes(item.id))) return failure(request, "evidence_id_collision"); const built = patch(request, signals, evidence, contract); if (built.missingPromises.length) return issueRewrite(request, built.missingPromises.map((id) => ({ ruleId: `promise.${id}.insufficient_evidence`, severity: "rewrite" })), deps, consumeTicket, after, artifactHash); const ledgerPatch = built.patch; const issued = permit(request, artifactHash, evidence, ledgerPatch, deps); const issuedAuthorization = { kind: "permit" as const, permitId: issued.permitId, permitDigest: publicationPermitDigest(issued), context: publicationPermitContext(issued) }; if (!await consumeTicketSafely(consumeTicket, casInput(request, after, artifactHash, issued.permitId, "accepted", evidence.map((item) => item.id), issuedAuthorization))) return failure(request, "ticket_reused");
  return { ok: true, value: { status: "accepted", artifactKind: request.artifact.kind, artifactHash, permit: issued, evidence, ledgerPatch, canonFactCandidates: built.candidates } };
}
