import { createHmac, createHash, timingSafeEqual } from "node:crypto";
import type { CanonFactCandidateV2, ObservableSignalV2 } from "../../src/types";
import { evidenceFromClaim, groundClaim, hashArtifact, sourceForArtifact, type EvidenceFinding, type GroundedClaim } from "./evidence";
import { canonicalAuthorizationPayload, sameMac, signExperiencePlan, verifyExperienceStageTicket } from "./scheduler";
import type { AssessExperienceRequest, AssessmentState, AssessorDependencies, ExperienceAssessment, ExperienceLedgerPatch, ExperienceOperationResult, ExperiencePublicationPermit, ExperienceRepairToken, ExperienceStagePlan, PublicationPermitContext, SemanticEvidenceClaim } from "./types";
import { isRuleAdapterId, runRuleAdapter } from "./ruleAdapters";

const permitDomain = "reading-experience:permit:v1";
const repairDomain = "reading-experience:repair:v1";
const invalidModel = (jobId: string): ExperienceOperationResult<never> => ({ ok: false, error: { code: "invalid_model_output", message: "Semantic judge returned an invalid verdict.", stage: "assessment", retryable: false, jobId } });
const unavailable = (jobId: string): ExperienceOperationResult<never> => ({ ok: false, error: { code: "model_unavailable", message: "Semantic judge is unavailable.", stage: "assessment", retryable: true, jobId } });
const freeze = <T>(value: T): T => { if (value && typeof value === "object" && !Object.isFrozen(value)) { for (const child of Object.values(value as object)) freeze(child); Object.freeze(value); } return value; };
const snapshot = <T>(value: T): T | undefined => { try { return freeze(structuredClone(value)); } catch { return undefined; } };
const sign = (domain: string, payload: unknown, secret: string): string => createHmac("sha256", secret).update(domain).update("\u001f").update(canonicalAuthorizationPayload(payload)).digest("base64url");
const equal = (left: string, right: string): boolean => { const a = Buffer.from(left, "base64url"); const b = Buffer.from(right, "base64url"); return a.length === b.length && timingSafeEqual(a, b); };
const artifactHashSafe = (request: AssessExperienceRequest): string => { try { return hashArtifact(request.artifact); } catch { return "invalid-artifact"; } };
const failure = (request: AssessExperienceRequest, id: string): ExperienceOperationResult<ExperienceAssessment> => ({ ok: true, value: { status: "rejected", artifactKind: request.artifact.kind, failedRuleIds: [id], message: "Assessment authorization is invalid." } });
const unique = (ids: string[]): string[] => [...new Set(ids)].sort();

function validArtifact(value: unknown): value is AssessExperienceRequest["artifact"] {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const item = value as Record<string, unknown>;
  if (item.kind === "blueprint") return Object.keys(item).every((key) => key === "kind" || key === "value") && item.value !== null && typeof item.value === "object" && !Array.isArray(item.value) && Object.keys(item.value as object).length > 0;
  if (item.kind !== "chapter" && item.kind !== "retcon_revision") return false;
  if (Object.keys(item).some((key) => !["kind", "chapterId", "revisionId", "title", "paragraphs"].includes(key))) return false;
  return typeof item.chapterId === "string" && !!item.chapterId.trim() && typeof item.revisionId === "string" && !!item.revisionId.trim() && typeof item.title === "string" && !!item.title.trim() && Array.isArray(item.paragraphs) && item.paragraphs.length > 0 && item.paragraphs.every((paragraph) => typeof paragraph === "string" && paragraph.length > 0);
}
function stageMatches(plan: ExperienceStagePlan, artifact: AssessExperienceRequest["artifact"]): boolean {
  if (artifact.kind === "blueprint") return plan.stage === "blueprint";
  if (artifact.kind === "retcon_revision") return plan.stage === "retcon";
  return plan.stage === "opening" || plan.stage === "continuation" || plan.stage === "rewrite";
}
function stateMatches(plan: ExperienceStagePlan, state: AssessmentState): boolean {
  return plan.ticket.activationId === state.activationId && plan.ticket.branchId === state.branchId && plan.ticket.expectedCanonVersion === state.canonVersion && plan.ticket.ledgerRevision === state.ledgerRevision && plan.ticket.attempt === state.attempt && !state.consumedTicketIds.includes(plan.ticket.id);
}
function validState(value: unknown): value is AssessmentState { if (!value || typeof value !== "object" || Array.isArray(value)) return false; const state = value as Record<string, unknown>; const allowed = ["activationId", "branchId", "canonVersion", "ledgerRevision", "attempt", "consumedTicketIds", "consumedPermitIds", "consumedRepairIds", "existingEvidenceIds", "chapterId", "revisionId", "expectedArtifactDigest"]; if (Object.keys(state).some((key) => !allowed.includes(key))) return false; return typeof state.activationId === "string" && !!state.activationId && typeof state.branchId === "string" && !!state.branchId && Number.isInteger(state.canonVersion) && Number.isInteger(state.ledgerRevision) && Number.isInteger(state.attempt) && [state.consumedTicketIds, state.consumedPermitIds, state.consumedRepairIds, state.existingEvidenceIds].every((list) => Array.isArray(list) && list.every((item) => typeof item === "string")); }
function authenticate(request: AssessExperienceRequest, deps: AssessorDependencies, state: AssessmentState): string | undefined {
  if (!validArtifact(request.artifact)) return "invalid_artifact";
  const plan = request.plan;
  if (!verifyExperienceStageTicket(plan.ticket, deps) || !Number.isFinite(Date.parse(plan.ticket.expiresAt))) return "ticket_tampered";
  if (Date.parse(plan.ticket.expiresAt) <= deps.now().getTime()) return "ticket_expired";
  const { authorizationMac, ...unsigned } = plan;
  if (!sameMac(authorizationMac, signExperiencePlan(unsigned, deps.ticketSecret))) return "plan_mismatch";
  if (plan.stage !== plan.ticket.stage || plan.artifactKind !== plan.ticket.artifactKind || plan.artifactKind !== request.artifact.kind || !stageMatches(plan, request.artifact)) return "stage_mismatch";
  if (plan.ticket.contractRevisionId !== deps.contract.id || plan.ticket.ruleGraphVersion !== deps.contract.ruleGraphVersion || !stateMatches(plan, state)) return "state_mismatch";
  if (request.artifact.kind !== "blueprint" && (!plan.chapterId || !plan.revisionId || plan.chapterId !== request.artifact.chapterId || plan.revisionId !== request.artifact.revisionId || state.chapterId !== request.artifact.chapterId || state.revisionId !== request.artifact.revisionId)) return "artifact_binding_mismatch";
  return undefined;
}
function selectedSignals(plan: ExperienceStagePlan, deps: AssessorDependencies): ObservableSignalV2[] | undefined {
  const map = new Map(deps.contract.dimensions.flatMap((dimension) => dimension.observableSignals.map((signal) => [signal.id, signal] as const)));
  const signals: ObservableSignalV2[] = [];
  for (const dimension of plan.promptProjection.dimensions) for (const id of dimension.signalIds) { const signal = map.get(id); if (!signal || signal.dimensionId !== dimension.id || signals.some((candidate) => candidate.id === id)) return undefined; signals.push(signal); }
  if (!signals.length || plan.evidenceSchema.length !== signals.length || plan.ruleAdapterIds.some((id) => !isRuleAdapterId(id))) return undefined;
  const expectedAdapters = deps.contract.prohibitions.flatMap((item) => item.ruleAdapterId && isRuleAdapterId(item.ruleAdapterId) ? [item.ruleAdapterId] : []).sort(); if ([...plan.ruleAdapterIds].sort().join("|") !== expectedAdapters.join("|")) return undefined;
  return plan.evidenceSchema.every((policy, index) => canonicalAuthorizationPayload(policy) === canonicalAuthorizationPayload(signals[index].verification)) ? signals : undefined;
}
const unrealized = /\b(?:not|never|cannot|can't|did not|didn't|plan(?:s|ned)?|intend(?:s|ed)?|attempt(?:s|ed)?|fail(?:s|ed)?|dream(?:s|ed)?|simulation|predict(?:s|ed)?|would|could|might|hearsay|rumou?r|label|descriptor)\b|(?:没有|未能|计划|打算|试图|失败|梦境|模拟|预测|据说|标签|描述词)/i;
function localFinding(source: string, claim: SemanticEvidenceClaim, grounded: GroundedClaim, signal: ObservableSignalV2, roles: ExperienceStagePlan["roleBindings"]): EvidenceFinding | undefined {
  const text = grounded.anchors.map((anchor) => source.slice(anchor.start, anchor.end)).join(" "); const slots = claim.slots ?? {};
  if (unrealized.test(text)) return { ruleId: "evidence.not_realized", severity: "rewrite", dimensionId: signal.dimensionId };
  const present = (slot: string) => typeof slots[slot as keyof typeof slots] === "string" && (slots[slot as keyof typeof slots] as string).trim() && text.toLocaleLowerCase().includes((slots[slot as keyof typeof slots] as string).toLocaleLowerCase());
  const required: Record<string, string[]> = { mechanic: ["actor", "action", "object", "outcome"], protagonist_action: ["actor", "action", "outcome"], conflict_outcome: ["actor", "action", "outcome"], world_reaction: ["actor", "reaction", "outcome"], relationship: ["actor", "action", "reciprocalAction", "relationshipChange"] };
  const policyRequired = signal.verification.kind === "event_slots" ? signal.verification.requiredSlots : [];
  if ([...policyRequired, ...(required[signal.kind] ?? [])].some((slot) => !present(slot))) return { ruleId: "evidence.required_slot_missing", severity: "rewrite", dimensionId: signal.dimensionId };
  if (["protagonist_action", "conflict_outcome", "mechanic"].includes(signal.kind) && (!roles.protagonistId || !roles.aliases.includes(slots.actor ?? ""))) return { ruleId: "evidence.helper_substitution", severity: "rewrite", dimensionId: signal.dimensionId };
  if (Object.entries(claim.slotAnchorIndices).some(([slot, index]) => !Number.isInteger(index) || index! < 0 || index! >= grounded.anchors.length || !slots[slot as keyof typeof slots] || !grounded.anchors[index!].text.includes(slots[slot as keyof typeof slots]!))) return { ruleId: "evidence.slot_anchor_not_grounded", severity: "rewrite", dimensionId: signal.dimensionId };
  if (signal.semanticSlots && Object.entries(signal.semanticSlots).some(([name, expected]) => slots[name as keyof typeof slots] !== expected)) return { ruleId: "evidence.binding_mismatch", severity: "rewrite", dimensionId: signal.dimensionId };
  return undefined;
}
function validVerdict(value: unknown): value is { version: 1; claims: SemanticEvidenceClaim[]; sharedCause: { eventId: string; supported: boolean; confidence: number; anchors: Array<{ start: number; end: number; quote: string }> } } {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false; const record = value as Record<string, unknown>;
  if (record.version !== 1 || !Array.isArray(record.claims) || Object.keys(record).some((key) => !["version", "claims", "sharedCause"].includes(key))) return false;
  const shared = record.sharedCause as Record<string, unknown> | undefined; if (!shared || typeof shared.eventId !== "string" || typeof shared.supported !== "boolean" || typeof shared.confidence !== "number" || !Number.isFinite(shared.confidence) || !Array.isArray(shared.anchors) || Object.keys(shared).some((key) => !["eventId", "supported", "confidence", "anchors"].includes(key))) return false;
  const anchorValid = (anchor: unknown) => !!anchor && typeof anchor === "object" && !Array.isArray(anchor) && Number.isInteger((anchor as Record<string, unknown>).start) && Number.isInteger((anchor as Record<string, unknown>).end) && typeof (anchor as Record<string, unknown>).quote === "string" && Object.keys(anchor as object).every((key) => ["start", "end", "quote"].includes(key)); if (!shared.anchors.every(anchorValid)) return false;
  return record.claims.every((value) => { if (!value || typeof value !== "object" || Array.isArray(value)) return false; const claim = value as Record<string, unknown>; if (Object.keys(claim).some((key) => !["version", "eventId", "dimensionId", "signalId", "supported", "confidence", "anchors", "slotAnchorIndices", "slots", "metrics"].includes(key)) || claim.version !== 1 || typeof claim.eventId !== "string" || !claim.eventId || typeof claim.dimensionId !== "string" || typeof claim.signalId !== "string" || typeof claim.supported !== "boolean" || typeof claim.confidence !== "number" || !Number.isFinite(claim.confidence) || !Array.isArray(claim.anchors) || !claim.slotAnchorIndices || typeof claim.slotAnchorIndices !== "object" || Array.isArray(claim.slotAnchorIndices)) return false; if (claim.metrics !== undefined && (!claim.metrics || typeof claim.metrics !== "object" || Array.isArray(claim.metrics) || Object.values(claim.metrics as Record<string, unknown>).some((metric) => typeof metric !== "number" || !Number.isFinite(metric)))) return false; if (claim.slots !== undefined && (!claim.slots || typeof claim.slots !== "object" || Array.isArray(claim.slots) || Object.keys(claim.slots as Record<string, unknown>).some((key) => !["actor", "action", "object", "feedback", "outcome", "reaction", "reciprocalAction", "relationshipChange"].includes(key)) || Object.values(claim.slots as Record<string, unknown>).some((slot) => typeof slot !== "string"))) return false; return claim.anchors.every(anchorValid); });
}
function ledgerHash(patch: ExperienceLedgerPatch): string { return createHash("sha256").update(canonicalAuthorizationPayload(patch)).digest("hex"); }
function permit(request: AssessExperienceRequest, artifactHash: string, evidenceIds: string[], patch: ExperienceLedgerPatch, deps: AssessorDependencies): ExperiencePublicationPermit {
  const artifact = request.artifact; if (artifact.kind === "blueprint") throw new Error("invalid permit artifact"); const expiresAt = new Date(deps.now().getTime() + (deps.permitTtlMs ?? 600_000)).toISOString();
  const unsigned = { version: 1 as const, ticketId: request.plan.ticket.id, jobId: request.plan.ticket.jobId, attempt: request.plan.ticket.attempt, contractRevisionId: request.plan.ticket.contractRevisionId, activationId: request.plan.ticket.activationId, branchId: request.plan.ticket.branchId, chapterId: artifact.chapterId, revisionId: artifact.revisionId, artifactHash, stage: request.plan.stage, artifactKind: request.plan.artifactKind, ruleGraphVersion: request.plan.ticket.ruleGraphVersion, expectedCanonVersion: request.plan.ticket.expectedCanonVersion, ledgerRevision: request.plan.ticket.ledgerRevision, evidenceIds: [...evidenceIds].sort(), ledgerPatchHash: ledgerHash(patch), permitId: `permit_${createHash("sha256").update(`${request.plan.ticket.id}\u001f${artifactHash}\u001f${expiresAt}`).digest("base64url")}`, expiresAt };
  return { ...unsigned, signature: sign(permitDomain, unsigned, deps.ticketSecret) };
}
export function verifyPublicationPermit(value: unknown, context: PublicationPermitContext, secret: string, now: Date): boolean {
  try { const contextKeys = ["ticketId", "jobId", "attempt", "contractRevisionId", "activationId", "branchId", "stage", "artifactKind", "ruleGraphVersion", "expectedCanonVersion", "ledgerRevision", "chapterId", "revisionId", "artifactHash", "evidenceIds", "ledgerPatchHash"].sort(); if (!context || typeof context !== "object" || Object.keys(context).sort().join("|") !== contextKeys.join("|")) return false; if (!value || typeof value !== "object" || Array.isArray(value)) return false; const permit = value as ExperiencePublicationPermit; const permitKeys = [...contextKeys, "version", "permitId", "expiresAt", "signature"].sort(); if (Object.keys(value).sort().join("|") !== permitKeys.join("|")) return false; const { signature, ...unsigned } = permit; if (permit.version !== 1 || typeof signature !== "string" || !permit.permitId || !Number.isFinite(Date.parse(permit.expiresAt)) || Date.parse(permit.expiresAt) <= now.getTime()) return false; if (!equal(signature, sign(permitDomain, unsigned, secret))) return false; return Object.entries(context).every(([key, expected]) => canonicalAuthorizationPayload((permit as unknown as Record<string, unknown>)[key]) === canonicalAuthorizationPayload(expected)); } catch { return false; }
}
export async function consumePublicationPermit(value: unknown, context: PublicationPermitContext, deps: AssessorDependencies): Promise<boolean> { if (!verifyPublicationPermit(value, context, deps.ticketSecret, deps.now())) return false; const permit = value as ExperiencePublicationPermit; const state = await deps.statePort.read({ ticketId: permit.ticketId, jobId: permit.jobId }); if (state.consumedPermitIds.includes(permit.permitId)) return false; return !!await deps.statePort.consumePermit({ permitId: permit.permitId, ticketId: permit.ticketId }); }
function repair(request: AssessExperienceRequest, ids: string[], deps: AssessorDependencies): ExperienceRepairToken { const artifact = request.artifact; const expiresAt = new Date(deps.now().getTime() + (deps.repairTtlMs ?? 300_000)).toISOString(); const unsigned = { version: 1 as const, repairId: `repair_${createHash("sha256").update(`${request.plan.ticket.id}\u001f${artifactHashSafe(request)}\u001f${expiresAt}`).digest("base64url")}`, ticketId: request.plan.ticket.id, jobId: request.plan.ticket.jobId, attempt: request.plan.ticket.attempt, contractRevisionId: request.plan.ticket.contractRevisionId, activationId: request.plan.ticket.activationId, branchId: request.plan.ticket.branchId, stage: request.plan.stage, artifactKind: request.plan.artifactKind, expectedCanonVersion: request.plan.ticket.expectedCanonVersion, ledgerRevision: request.plan.ticket.ledgerRevision, ...(artifact.kind === "blueprint" ? {} : { chapterId: artifact.chapterId, revisionId: artifact.revisionId }), artifactHash: artifactHashSafe(request), failedRuleIds: unique(ids), expiresAt }; return { ...unsigned, signature: sign(repairDomain, unsigned, deps.ticketSecret) }; }
export function verifyRepairToken(value: unknown, context: Omit<PublicationPermitContext, "ruleGraphVersion" | "evidenceIds" | "ledgerPatchHash"> & { failedRuleIds: readonly string[] }, secret: string, now: Date): boolean { try { const required = ["ticketId", "jobId", "attempt", "contractRevisionId", "activationId", "branchId", "stage", "artifactKind", "expectedCanonVersion", "ledgerRevision", "chapterId", "revisionId", "artifactHash", "failedRuleIds"].sort(); if (!context || typeof context !== "object" || Object.keys(context).sort().join("|") !== required.join("|") || !value || typeof value !== "object" || Array.isArray(value)) return false; const token = value as ExperienceRepairToken; const { signature, ...unsigned } = token; const expiry = Date.parse(token.expiresAt); if (token.version !== 1 || typeof signature !== "string" || !token.repairId || !Number.isFinite(expiry) || expiry <= now.getTime() || !equal(signature, sign(repairDomain, unsigned, secret))) return false; return Object.entries(context).every(([key, expected]) => canonicalAuthorizationPayload((token as unknown as Record<string, unknown>)[key]) === canonicalAuthorizationPayload(expected)); } catch { return false; } }
export async function consumeRepairToken(value: unknown, context: Omit<PublicationPermitContext, "ruleGraphVersion" | "evidenceIds" | "ledgerPatchHash"> & { failedRuleIds: readonly string[] }, deps: AssessorDependencies): Promise<boolean> { if (!verifyRepairToken(value, context, deps.ticketSecret, deps.now())) return false; const token = value as ExperienceRepairToken; const state = await deps.statePort.read({ ticketId: token.ticketId, jobId: token.jobId }); if (state.consumedRepairIds.includes(token.repairId)) return false; return !!await deps.statePort.consumeRepair({ repairId: token.repairId, ticketId: token.ticketId }); }
function rewrite(request: AssessExperienceRequest, findings: EvidenceFinding[], deps: AssessorDependencies): ExperienceOperationResult<ExperienceAssessment> { const blocking = findings.find((finding) => finding.severity === "rejected"); if (blocking) return failure(request, blocking.ruleId); const ids = unique(findings.map((finding) => finding.ruleId)); return { ok: true, value: { status: "rewrite", artifactKind: request.artifact.kind, failedRuleIds: ids, repairToken: repair(request, ids, deps), message: "Evidence must be grounded in the submitted artifact." } }; }
function casInput(request: AssessExperienceRequest, artifactHash: string, outcomeId: string, outcome: "accepted" | "rewrite" | "rejected" | "blueprint"): Parameters<AssessorDependencies["statePort"]["consumeTicket"]>[0] { return { ticketId: request.plan.ticket.id, artifactHash, outcomeId, outcome, expected: { activationId: request.plan.ticket.activationId, branchId: request.plan.ticket.branchId, canonVersion: request.plan.ticket.expectedCanonVersion, ledgerRevision: request.plan.ticket.ledgerRevision, attempt: request.plan.ticket.attempt, ...(request.plan.chapterId ? { chapterId: request.plan.chapterId } : {}), ...(request.plan.revisionId ? { revisionId: request.plan.revisionId } : {}), ...(request.plan.expectedArtifactDigest ? { expectedArtifactDigest: request.plan.expectedArtifactDigest } : {}) } }; }
async function issueRewrite(request: AssessExperienceRequest, findings: EvidenceFinding[], deps: AssessorDependencies, consume: AssessorDependencies["statePort"]["consumeTicket"], artifactHash: string): Promise<ExperienceOperationResult<ExperienceAssessment>> { const result = rewrite(request, findings, deps); let outcomeId = `blocked_${findings.map((finding) => finding.ruleId).join("_")}`; let outcome: "rewrite" | "rejected" = "rejected"; if (result.ok && result.value.status === "rewrite") { outcomeId = result.value.repairToken.repairId; outcome = "rewrite"; } if (!await consume(casInput(request, artifactHash, outcomeId, outcome))) return failure(request, "ticket_reused"); return result; }
function validBlueprint(value: Record<string, unknown>, plan: ExperienceStagePlan): boolean { const keys = Object.keys(value).sort(); if (keys.join("|") !== ["axisSignalIds", "chapters", "endingContract", "hardPromiseIds", "meta", "protagonist", "schemaVersion", "title"].sort().join("|")) return false; const protagonist = value.protagonist as Record<string, unknown> | undefined; const ending = value.endingContract as Record<string, unknown> | undefined; const meta = value.meta as Record<string, unknown> | undefined; return value.schemaVersion === 1 && typeof value.title === "string" && !!value.title.trim() && !!protagonist && protagonist.id === plan.roleBindings.protagonistId && !!ending && typeof ending.target === "string" && !!ending.target.trim() && Array.isArray(value.chapters) && value.chapters.length > 0 && Array.isArray(value.axisSignalIds) && plan.promptProjection.dimensions.every((dimension) => dimension.signalIds.every((id) => (value.axisSignalIds as unknown[]).includes(id))) && Array.isArray(value.hardPromiseIds) && plan.hardPresencePromiseIds.every((id) => (value.hardPromiseIds as unknown[]).includes(id)) && !!meta && meta.prohibitionsSatisfied === true; }
function patch(request: AssessExperienceRequest, signals: ObservableSignalV2[], evidence: ReturnType<typeof evidenceFromClaim>[], deps: AssessorDependencies): { patch: ExperienceLedgerPatch; candidates: CanonFactCandidateV2[]; missingPromises: string[] } {
  const deliveredSignalIdsByDimension = Object.fromEntries(request.plan.promptProjection.dimensions.map((dimension) => [dimension.id, evidence.filter((item) => item.dimensionId === dimension.id).map((item) => item.signalId)]));
  const candidates = evidence.flatMap((item) => { const signal = signals.find((candidate) => candidate.id === item.signalId)!; if (!(["cross_chapter", "whole_story"] as string[]).includes(signal.persistence) || !(item.observation.outcome || item.observation.relationshipOrStateChange)) return []; const kind: CanonFactCandidateV2["kind"] = signal.kind === "mechanic" ? "mechanic" : signal.kind === "relationship" ? "relationship" : "outcome"; return [{ id: createHash("sha256").update(canonicalAuthorizationPayload([item.id, item.chapterRevisionId, kind])).digest("base64url"), evidenceId: item.id, revisionId: item.chapterRevisionId, dimensionId: item.dimensionId, signalId: item.signalId, kind, observation: structuredClone(item.observation), anchors: item.anchors.map((anchor) => ({ ...anchor })) }]; });
  const persistentResultsByDimension = Object.fromEntries(request.plan.promptProjection.dimensions.map((dimension) => [dimension.id, candidates.filter((candidate) => candidate.dimensionId === dimension.id).map((candidate) => ({ id: candidate.id, revisionId: candidate.revisionId, kind: candidate.kind }))]));
  const promiseEvidenceLinks: Record<string, string[]> = {}; const missingPromises: string[] = [];
  for (const promiseId of request.plan.duePromiseIds) { const promise = deps.contract.promises.find((item) => item.id === promiseId); if (!promise) { missingPromises.push(promiseId); continue; } const relevant = evidence.filter((item) => promise.dimensionId === "both" || item.dimensionId === promise.dimensionId); if (new Set(relevant.map((item) => item.signalId)).size < promise.minimumSignals) missingPromises.push(promiseId); else promiseEvidenceLinks[promiseId] = relevant.map((item) => item.id); }
  const newDebtsByDimension = Object.fromEntries(request.plan.promptProjection.dimensions.map((dimension) => [dimension.id, request.plan.newDebts.filter((debt) => debt.dimensionId === dimension.id).map(({ promiseId, dueByChapter }) => ({ promiseId, dueByChapter }))]));
  return { patch: { ticket: { ...request.plan.ticket }, expectedRevision: request.plan.ticket.ledgerRevision, nextRevision: request.plan.ticket.ledgerRevision + 1, contractRevisionId: request.plan.ticket.contractRevisionId, activationId: request.plan.ticket.activationId, branchId: request.plan.ticket.branchId, expectedCanonVersion: request.plan.ticket.expectedCanonVersion, chapterNumber: request.plan.chapterNumber, deliveredSignalIdsByDimension, persistentResultsByDimension, newDebtsByDimension, deliveredPromiseIds: Object.keys(promiseEvidenceLinks), evidenceIds: evidence.map((item) => item.id), promiseEvidenceLinks }, candidates, missingPromises };
}

export async function assessExperience(input: AssessExperienceRequest, inputDeps: AssessorDependencies): Promise<ExperienceOperationResult<ExperienceAssessment>> {
  const ticketSecret = `${inputDeps.ticketSecret}`; const now = inputDeps.now.bind(inputDeps); const judge = inputDeps.semanticJudgePort?.judge?.bind(inputDeps.semanticJudgePort); const judgeTimeoutMs = inputDeps.judgeTimeoutMs ?? 15_000;
  const request = snapshot(input); const contract = snapshot(inputDeps.contract); if (!request || !contract || !validArtifact(request.artifact)) return failure(input, "invalid_artifact");
  const deps = { ...inputDeps, ticketSecret, now, contract }; const read = inputDeps.statePort?.read?.bind(inputDeps.statePort); const consumeTicket = inputDeps.statePort?.consumeTicket?.bind(inputDeps.statePort); if (!read || !consumeTicket || !judge) return failure(request, "state_unavailable");
  let before: AssessmentState; try { const value = snapshot(await read({ ticketId: request.plan.ticket.id, jobId: request.plan.ticket.jobId })); if (!validState(value)) return failure(request, "state_unavailable"); before = freeze(value); } catch { return failure(request, "state_unavailable"); }
  const auth = authenticate(request, deps, before); if (auth) return failure(request, auth); const signals = selectedSignals(request.plan, deps); if (!signals) return failure(request, "plan_mismatch");
  let source: string; let artifactHash: string; try { source = sourceForArtifact(request.artifact); artifactHash = hashArtifact(request.artifact); } catch { return failure(request, "invalid_artifact"); }
  if (request.artifact.kind !== "blueprint" && (!before.expectedArtifactDigest || !request.plan.expectedArtifactDigest || before.expectedArtifactDigest !== artifactHash || request.plan.expectedArtifactDigest !== artifactHash)) return failure(request, "artifact_digest_mismatch");
  if (request.artifact.kind === "blueprint") { const blueprint = request.artifact.value as Record<string, unknown>; if (!validBlueprint(blueprint, request.plan)) return issueRewrite(request, [{ ruleId: "blueprint.invalid_manifest", severity: "rewrite" }], deps, consumeTicket, artifactHash); if (!await consumeTicket(casInput(request, artifactHash, `blueprint_${artifactHash}`, "blueprint"))) return failure(request, "ticket_reused"); return { ok: true, value: { status: "accepted", artifactKind: "blueprint", artifactHash } }; }
  const unknownAdapter = contract.prohibitions.find((prohibition) => prohibition.ruleAdapterId && !isRuleAdapterId(prohibition.ruleAdapterId)); if (unknownAdapter) return failure(request, "plan_mismatch"); const adapterFinding = contract.prohibitions.find((prohibition) => prohibition.ruleAdapterId && isRuleAdapterId(prohibition.ruleAdapterId) && runRuleAdapter(prohibition.ruleAdapterId, source)); if (adapterFinding) return issueRewrite(request, [{ ruleId: adapterFinding.id, severity: adapterFinding.severity === "block" ? "rejected" : "rewrite" }], deps, consumeTicket, artifactHash);
  const judgeCase = freeze(snapshot({ version: 1 as const, contractRevisionId: contract.id, stage: request.plan.stage, artifactKind: request.artifact.kind, source, sourceHash: artifactHash, synthesis: snapshot(contract.synthesis)!, signals: signals.map((signal) => { const dimension = contract.dimensions.find((item) => item.id === signal.dimensionId)!; const projection = request.plan.promptProjection.dimensions.find((item) => item.id === signal.dimensionId)!; return { dimensionId: signal.dimensionId, signalId: signal.id, kind: signal.kind, interpretation: dimension.interpretation, description: signal.description, semanticSlots: signal.semanticSlots ? { ...signal.semanticSlots } : undefined, policy: snapshot(signal.verification)!, canonFactReferences: projection.factReferences.map((fact) => ({ ...fact })), prohibitions: [...dimension.prohibitions, ...contract.prohibitions.filter((item) => item.dimensionId === "both")].map(({ id, kind, severity, ruleAdapterId }) => ({ id, kind, severity, ...(ruleAdapterId ? { ruleAdapterId } : {}) })) }; }) }))!;
  let verdict: unknown; const controller = new AbortController(); let timer: ReturnType<typeof setTimeout> | undefined; try { const deadline = new Promise<never>((_, reject) => { timer = setTimeout(() => { controller.abort(); reject(new Error("timeout")); }, judgeTimeoutMs); timer.unref?.(); }); verdict = await Promise.race([judge(judgeCase, { signal: controller.signal }), deadline]); } catch { return unavailable(request.plan.ticket.jobId); } finally { if (timer) clearTimeout(timer); }
  verdict = snapshot(verdict); if (!validVerdict(verdict)) return invalidModel(request.plan.ticket.jobId); freeze(verdict);
  const sharedDimensions = new Set(verdict.claims.filter((claim) => claim.eventId === verdict.sharedCause.eventId).map((claim) => claim.dimensionId)); if (!verdict.sharedCause.supported || verdict.sharedCause.confidence < 0 || verdict.sharedCause.confidence > 1 || verdict.sharedCause.anchors.some((anchor) => anchor.start < 0 || anchor.end > source.length || anchor.end <= anchor.start || source.slice(anchor.start, anchor.end) !== anchor.quote) || sharedDimensions.size < 2) return issueRewrite(request, [{ ruleId: "evidence.shared_cause_unsupported", severity: "rewrite" }], deps, consumeTicket, artifactHash);
  let after: AssessmentState; try { const value = snapshot(await read({ ticketId: request.plan.ticket.id, jobId: request.plan.ticket.jobId })); if (!validState(value)) return failure(request, "state_unavailable"); after = freeze(value); } catch { return failure(request, "state_unavailable"); } if (!stateMatches(request.plan, after) || canonicalAuthorizationPayload(before) !== canonicalAuthorizationPayload(after)) return failure(request, "state_changed");
  const artifact = request.artifact;
  const claims = verdict.claims; if (claims.length !== signals.length || new Set(claims.map((claim) => `${claim.dimensionId}:${claim.signalId}`)).size !== claims.length) return invalidModel(request.plan.ticket.jobId);
  const findings: EvidenceFinding[] = []; const grounded: Array<{ signal: ObservableSignalV2; value: GroundedClaim }> = []; const spans: Array<{ dimensionId: string; start: number; end: number }> = [];
  for (const claim of claims) { const signal = signals.find((candidate) => candidate.id === claim.signalId && candidate.dimensionId === claim.dimensionId); if (!signal) return invalidModel(request.plan.ticket.jobId); if (!claim.supported) { findings.push({ ruleId: "evidence.judge_unsupported", severity: "rewrite" }); continue; } const value = groundClaim(source, claim, signal); if ("ruleId" in value) { if (value.ruleId === "invalid_model_output") return invalidModel(request.plan.ticket.jobId); findings.push(value); continue; } const local = localFinding(source, claim, value, signal, request.plan.roleBindings); if (local) { findings.push(local); continue; } for (const anchor of value.anchors) { if (spans.some((span) => anchor.start < span.end && span.start < anchor.end)) findings.push({ ruleId: "evidence.double_counted_span", severity: "rewrite" }); spans.push({ dimensionId: signal.dimensionId, start: anchor.start, end: anchor.end }); } grounded.push({ signal, value }); }
  if (findings.length) return issueRewrite(request, findings, deps, consumeTicket, artifactHash);
  const evidence = grounded.map(({ signal, value }) => evidenceFromClaim({ id: createHash("sha256").update(canonicalAuthorizationPayload([request.plan.ticket.id, request.plan.ticket.jobId, request.plan.ticket.attempt, request.plan.ticket.contractRevisionId, request.plan.ticket.activationId, request.plan.ticket.branchId, request.plan.stage, artifact.kind, artifact.chapterId, artifact.revisionId, artifactHash, signal.dimensionId, signal.id, value.claim.eventId])).digest("base64url"), contractRevisionId: request.plan.ticket.contractRevisionId, activationId: request.plan.ticket.activationId, branchId: request.plan.ticket.branchId, chapterId: artifact.chapterId, revisionId: artifact.revisionId, sourceHash: artifactHash, ticketId: request.plan.ticket.id, jobId: request.plan.ticket.jobId, attempt: request.plan.ticket.attempt, stage: request.plan.stage, artifactKind: artifact.kind, ruleGraphVersion: request.plan.ticket.ruleGraphVersion, expectedCanonVersion: request.plan.ticket.expectedCanonVersion, ledgerRevision: request.plan.ticket.ledgerRevision, grounded: value }));
  if (new Set(evidence.map((item) => item.id)).size !== evidence.length || evidence.some((item) => before.existingEvidenceIds.includes(item.id))) return failure(request, "evidence_id_collision"); const built = patch(request, signals, evidence, deps); if (built.missingPromises.length) return issueRewrite(request, built.missingPromises.map((id) => ({ ruleId: `promise.${id}.insufficient_evidence`, severity: "rewrite" })), deps, consumeTicket, artifactHash); const ledgerPatch = built.patch; const issued = permit(request, artifactHash, evidence.map((item) => item.id), ledgerPatch, deps); if (!await consumeTicket(casInput(request, artifactHash, issued.permitId, "accepted"))) return failure(request, "ticket_reused");
  return { ok: true, value: { status: "accepted", artifactKind: request.artifact.kind, artifactHash, permit: issued, evidence, ledgerPatch, canonFactCandidates: built.candidates } };
}
